# fly.toml app configuration for production environment (www.bibcal.org)
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bibcal-production'
primary_region = 'arn'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
dockerfile = 'Dockerfile'

[env]
PORT = '8080'
HOST = '0.0.0.0'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1    # Keep at least one instance running for production
processes = ['app']

[http_service.concurrency]
type = "connections"
hard_limit = 1000
soft_limit = 500

[[http_service.checks]]
interval = "10s"
timeout = "5s"
grace_period = "30s"
method = "GET"
path = "/health"

[[http_service.domains]]
name = "www.bibcal.org"
zone_id = ""

[[http_service.domains]]
name = "bibcal.org"
zone_id = ""

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
