name: Deploy to Production

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'  # Tags with semantic versioning format (e.g., 0.7.6)

jobs:
  deploy:
    name: Deploy to www.bibcal.org
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        
      - name: Deploy to Production
        run: flyctl deploy --config fly.production.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          LOCATIONIQ_API_KEY: ${{ secrets.LOCATIONIQ_API_KEY }}
          IPGEOLOCATION_API_KEY: ${{ secrets.IPGEOLOCATION_API_KEY }}
          
      - name: Verify Deployment
        run: |
          echo "Waiting for deployment to complete..."
          sleep 30
          curl -sSf https://www.bibcal.org/health || (echo "Deployment verification failed" && exit 1)
          echo "Deployment successful!"