name: Test Suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.1
        with:
          clj-kondo: 'latest'

      - uses: actions/checkout@v3

      - name: Get clj-kondo version
        run: clj-kondo --version

      - name: clj-kondo
        run: clj-kondo --lint src

      # Disabled until kibit allows disabling select rules.
      # - name: Install lein deps
      #   run: lein deps

      # - name: Lein Kibit
      #   run: lein kibit

  lein_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup leiningen
      uses: DeLaGuardo/setup-clojure@12.1
      with:
        lein: 'latest'

    - name: Install dependencies
      run: lein deps

    - name: Check Java version
      run: java -version
    
    - name: Run tests
      run: lein test
      env:
        LOCATIONIQ_API_KEY: ${{ secrets.LOCATIONIQ_API_KEY }}
        IPGEOLOCATION_API_KEY: ${{ secrets.IPGEOLOCATION_API_KEY }}
